---
title: "Support Vector Machine"
author: "Mehmet ÇAY"
date: "2022-09-22"
output: 
  html_document: 
    toc: yes
    highlight: zenburn
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Support Vector Machine

In order to understand what we are going to do here you need to check internet about Support Vector Machine. [Here](https://www.javatpoint.com/machine-learning-support-vector-machine-algorithm) is your first place.
```{r}

breastCancer <- read.csv("C:/Users/Mehmet ÇAY/Desktop/R/Regressions/Regressions/breast-cancer.csv")

modelData <- breastCancer

str(modelData)
varNames <- names(modelData)
modelData <- modelData[, -which(varNames == 'X' | varNames == 'id')]
varNames <- names(modelData)

selectedVars <- c("diagnosis" ,  "radius_mean" ,"texture_mean"  ,         
                   "perimeter_mean"  ,"area_mean" ,"smoothness_mean" ,       
                  "compactness_mean" ,"concavity_mean", "concave.points_mean" ,
                  "symmetry_mean" ,"fractal_dimension_mean")

modelDataSelected <- modelData[selectedVars]
View(modelDataSelected)


plot(modelDataSelected$radius_mean , modelDataSelected$texture_mean , pch = 19,
      col = c('blue' , 'orange')[as.factor(modelDataSelected$diagnosis)] )


plot(modelDataSelected$area_mean , modelDataSelected$perimeter_mean , pch = 19,
     col = c('blue' , 'orange')[as.factor(modelDataSelected$diagnosis)] )

plot(modelDataSelected$smoothness_mean, modelDataSelected$compactness_mean , pch = 19,
     col = c('blue' , 'orange')[as.factor(modelDataSelected$diagnosis)] )

plot(modelDataSelected$radius_mean, modelDataSelected$compactness_mean , pch = 19,
     col = c('blue' , 'orange')[as.factor(modelDataSelected$diagnosis)] )


modelDataSelected$diagnosis <- as.factor(modelDataSelected$diagnosis)
class(modelDataSelected$diagnosis)


table(modelDataSelected$diagnosis)


set.seed(125) #Get trainset and testset
trainIndex <- sample(1:nrow(modelDataSelected) , size = 0.8*nrow(modelDataSelected))

trainSet <- modelDataSelected[ trainIndex,]
testSet <- modelDataSelected[-trainIndex,]

table(trainSet$diagnosis)
table(testSet$diagnosis)

head(trainSet)


```

Create Model
```{r}
library(e1071)
modelLinear <- svm( diagnosis ~ . , data  = trainSet , kernel = 'linear' )
modelRadial <- svm( diagnosis ~ . , data  = trainSet , kernel = 'radial' )

modelLinear
summary(modelLinear)
modelRadial$coefs
modelLinear$coefs
modelLinear$decision.values

```

Predict
```{r}

predLinear <- predict(modelLinear , testSet)
predRadial <- predict(modelRadial , testSet)


caret::confusionMatrix(predLinear , testSet$diagnosis)
caret::confusionMatrix(predRadial , testSet$diagnosis)

caret::confusionMatrix(predLinear , testSet$diagnosis , mode = "prec_recall")
caret::confusionMatrix(predRadial , testSet$diagnosis , mode = "prec_recall")


modelLinearP <- svm( diagnosis ~ . , data  = trainSet , kernel = 'linear' , probability = T)
modelRadialP <- svm( diagnosis ~ . , data  = trainSet , kernel = 'radial' , probability = T)

predLinearP <- predict(modelLinearP , testSet , probability = T)
attr(predLinearP , "probabilities")

```

Visualize Results
```{r}


plot(modelLinear , trainSet , radius_mean ~ texture_mean)
plot(modelLinear , testSet , radius_mean ~ texture_mean)
plot(modelLinear , testSet , perimeter_mean ~ area_mean)


plot(modelRadial , trainSet , radius_mean ~ texture_mean)
plot(modelRadial , testSet , radius_mean ~ texture_mean)
plot(modelRadial , testSet , perimeter_mean ~ area_mean)


```
Model Tunning
```{r}

library(e1071)

modelLinearTune <- tune(svm , diagnosis ~ . , data = trainSet ,
      kernel = "linear",
      ranges = list(gamma = 2^(-2:2) , cost = 2^(-4:2)),
      tunecontrol = tune.control(cross = 5)
     )
modelRadialTune <- tune(svm , diagnosis ~ . , data = trainSet ,
                        kernel = "radial",
                        ranges = list(gamma = 2^(-2:2) , cost = 2^(-4:2)),
                        tunecontrol = tune.control(cross = 5)
)

modelLinearTune
modelRadialTune

modelRadialTune$performances

predLinearTune <- predict(modelLinearTune$best.model , testSet)
predRadialTune <- predict(modelRadialTune$best.model , testSet)


caret::confusionMatrix(predLinearTune , testSet$diagnosis)
caret::confusionMatrix(predRadialTune , testSet$diagnosis)

caret::confusionMatrix(predLinearTune , testSet$diagnosis , mode = "prec_recall")
caret::confusionMatrix(predRadialTune , testSet$diagnosis , mode = "prec_recall")
```

